package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Run from anywhere but the repository root and the contract is simply not
// there. The message has to say so, because the mistake is easy and the raw
// "no such file" names a path that looks like a missing file rather than a
// wrong directory.
func TestRun_OutsideTheRepositoryRootSaysWhere(t *testing.T) {
	t.Chdir(t.TempDir())

	err := run(filepath.Join(t.TempDir(), "types.ts"), filepath.Join(t.TempDir(), "routes.ts"))
	if err == nil {
		t.Fatal("want an error with no contract to read, got none")
	}
	if !strings.Contains(err.Error(), "repository root") {
		t.Errorf("the error must name the cause, got %v", err)
	}
}

func TestRun_UnwritableTargetIsReported(t *testing.T) {
	root := repoRoot(t)
	t.Chdir(root)

	err := run(filepath.Join(t.TempDir(), "no-such-directory", "types.ts"),
		filepath.Join(t.TempDir(), "routes.ts"))
	if err == nil {
		t.Fatal("want an error for an unwritable target, got none")
	}
	if !strings.Contains(err.Error(), "write") {
		t.Errorf("the error must say what failed, got %v", err)
	}
}

// Both halves of the contract come out of one run: the shapes and the paths
// are one declaration, so a generator that wrote only the types would leave the
// client's paths to be regenerated by hand — the very step this removes.
func TestRun_WritesBothHalvesOfTheContract(t *testing.T) {
	root := repoRoot(t)
	t.Chdir(root)

	dir := t.TempDir()
	types := filepath.Join(dir, "types.ts")
	routes := filepath.Join(dir, "routes.ts")
	if err := run(types, routes); err != nil {
		t.Fatalf("run: %v", err)
	}

	for _, tc := range []struct{ target, marker string }{
		// The header is what tells a reader not to edit the file; without it
		// the generation is indistinguishable from a hand-written module.
		{types, "Do not edit"},
		{routes, "export const API = {"},
	} {
		out, err := os.ReadFile(tc.target)
		if err != nil {
			t.Fatalf("read back %s: %v", tc.target, err)
		}
		if !strings.Contains(string(out), "Do not edit") || !strings.Contains(string(out), tc.marker) {
			t.Errorf("%s is not the generated module:\n%s", tc.target, out)
		}
	}
}

// The routes half is written too, so an unwritable one is reported rather than
// leaving a run that says nothing and regenerated only half the contract.
func TestRun_UnwritableRoutesTargetIsReported(t *testing.T) {
	root := repoRoot(t)
	t.Chdir(root)

	err := run(filepath.Join(t.TempDir(), "types.ts"),
		filepath.Join(t.TempDir(), "no-such-directory", "routes.ts"))
	if err == nil {
		t.Fatal("want an error for an unwritable routes target, got none")
	}
	if !strings.Contains(err.Error(), "routes.ts") {
		t.Errorf("the error must name the file that failed, got %v", err)
	}
}

// repoRoot walks up from the test's own directory to the module root, so the
// tests do not depend on where `go test` was invoked.
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("no go.mod above the test directory")
		}
		dir = parent
	}
}
