/**
 * Generated from internal/store/tables.go and internal/store/schema.sql by
 * cmd/wiregen. Do not edit.
 *
 * The per-table half of the contract (ARCH-11, ADR-026): which tables travel
 * the sync protocol and on which feed (`tableSpecs`), every column each
 * table has and the text vocabularies its CHECK lists close (the schema), and
 * the columns a push may set (the whitelist). `make wire` regenerates it,
 * and the CI gate refuses a copy that has fallen behind either source.
 */

/** The syncable table names, named once (CODING_PRINCIPLES §4a). */
export const TABLE = {
  taskTags: 'task_tags',
  tags: 'tags',
  itemTags: 'item_tags',
  items: 'items',
  itemDependencies: 'item_dependencies',
  templates: 'templates',
  templateItems: 'template_items',
  templateIncludes: 'template_includes',
  templateItemTasks: 'template_item_tasks',
  templateTasks: 'template_tasks',
  tripSeries: 'trip_series',
  destinationProfiles: 'destination_profiles',
  destinationChecklistItems: 'destination_checklist_items',
  trips: 'trips',
  tripMembers: 'trip_members',
  tripTemplateSources: 'trip_template_sources',
  tripAppliedChanges: 'trip_applied_changes',
  tripItems: 'trip_items',
  travelers: 'travelers',
  containers: 'containers',
  comments: 'comments',
  noteAcks: 'note_acks',
  shoppingEntries: 'shopping_entries',
  excursions: 'excursions',
  excursionTravelers: 'excursion_travelers',
  excursionItems: 'excursion_items',
  excursionTracks: 'excursion_tracks',
  ideas: 'ideas',
  ideaVotes: 'idea_votes',
  ideaComments: 'idea_comments',
  ideaImages: 'idea_images',
  dayEntries: 'day_entries',
  dayEntryTravelers: 'day_entry_travelers',
  meals: 'meals',
  mealIngredients: 'meal_ingredients',
  ideaTracks: 'idea_tracks',
  tripGeneratedPositions: 'trip_generated_positions',
} as const

/** Any table that travels the sync protocol. */
export type SyncTable = (typeof TABLE)[keyof typeof TABLE]

/** The feed each table's changes travel on (Sync-API P-3). */
export const TABLE_PARTITION = {
  task_tags: 'master',
  tags: 'master',
  item_tags: 'master',
  items: 'master',
  item_dependencies: 'master',
  templates: 'master',
  template_items: 'master',
  template_includes: 'master',
  template_item_tasks: 'master',
  template_tasks: 'master',
  trip_series: 'master',
  destination_profiles: 'master',
  destination_checklist_items: 'master',
  trips: 'master',
  trip_members: 'master',
  trip_template_sources: 'master',
  trip_applied_changes: 'master',
  trip_items: 'trip',
  travelers: 'trip',
  containers: 'trip',
  comments: 'trip',
  note_acks: 'trip',
  shopping_entries: 'trip',
  excursions: 'trip',
  excursion_travelers: 'trip',
  excursion_items: 'trip',
  excursion_tracks: 'trip',
  ideas: 'trip',
  idea_votes: 'trip',
  idea_comments: 'trip',
  idea_images: 'trip',
  day_entries: 'trip',
  day_entry_travelers: 'trip',
  meals: 'trip',
  meal_ingredients: 'trip',
  idea_tracks: 'trip',
  trip_generated_positions: 'trip',
} as const

/** Every column of each table, in the schema's order. */
export const TABLE_COLUMNS = {
  task_tags: ['id', 'name', 'sort_order', 'icon', 'field_hlcs', 'updated_hlc'],
  tags: ['id', 'name', 'sort_order', 'icon', 'field_hlcs', 'updated_hlc'],
  item_tags: ['id', 'item_id', 'tag_id', 'position', 'field_hlcs', 'updated_hlc'],
  items: [
    'id',
    'name',
    'weight_grams',
    'value_cents',
    'created_by',
    'image_hash',
    'icon',
    'retired_at',
    'default_assignee_id',
    'merged_into_id',
    'field_hlcs',
    'updated_hlc',
  ],
  item_dependencies: [
    'id',
    'item_id',
    'depends_on_item_id',
    'mode',
    'quantity',
    'field_hlcs',
    'updated_hlc',
  ],
  templates: [
    'id',
    'owner_id',
    'name',
    'kind',
    'is_published',
    'icon',
    'retired_at',
    'field_hlcs',
    'updated_hlc',
  ],
  template_items: [
    'id',
    'template_id',
    'item_id',
    'quantity',
    'assignment',
    'dedup',
    'conditions',
    'default_mode',
    'late_packer',
    'field_hlcs',
    'updated_hlc',
  ],
  template_includes: ['id', 'template_id', 'included_template_id', 'field_hlcs', 'updated_hlc'],
  template_item_tasks: ['id', 'template_item_id', 'task', 'field_hlcs', 'updated_hlc'],
  template_tasks: ['id', 'template_id', 'task', 'phase', 'field_hlcs', 'updated_hlc'],
  trip_series: ['id', 'owner_id', 'name', 'default_attributes', 'field_hlcs', 'updated_hlc'],
  destination_profiles: ['id', 'series_id', 'notes', 'field_hlcs', 'updated_hlc'],
  destination_checklist_items: ['id', 'profile_id', 'label', 'mode', 'field_hlcs', 'updated_hlc'],
  trips: [
    'id',
    'series_id',
    'name',
    'year',
    'start_date',
    'end_date',
    'duration_days',
    'status',
    'attributes',
    'packing_closed_at',
    'imported',
    'created_by',
    'field_hlcs',
    'updated_hlc',
  ],
  trip_members: ['id', 'trip_id', 'user_id', 'role', 'field_hlcs', 'updated_hlc'],
  trip_template_sources: ['id', 'trip_id', 'template_id', 'field_hlcs', 'updated_hlc'],
  trip_applied_changes: [
    'id',
    'trip_id',
    'source_template_id',
    'source_template_name',
    'kind',
    'item_name',
    'detail',
    'created_at',
    'field_hlcs',
    'updated_hlc',
  ],
  trip_items: [
    'id',
    'trip_id',
    'source_item_id',
    'source_template_id',
    'name',
    'weight_grams',
    'value_cents',
    'category_name',
    'quantity',
    'packed_count',
    'state',
    'mode',
    'bought_from',
    'bought_at',
    'bought_by_user_id',
    'late_packer',
    'assigned_traveler_id',
    'packer_user_id',
    'packed_by_user_id',
    'packed_at',
    'container_id',
    'packing_now_by',
    'packing_now_at',
    'flag_unused',
    'flag_missing',
    'outbound_packed',
    'carried_over_at',
    'shopping_position',
    'field_hlcs',
    'updated_hlc',
  ],
  travelers: ['id', 'trip_id', 'name', 'linked_user_id', 'field_hlcs', 'updated_hlc'],
  containers: [
    'id',
    'trip_id',
    'name',
    'carrier_traveler_id',
    'max_weight_grams',
    'paired_container_id',
    'field_hlcs',
    'updated_hlc',
  ],
  comments: [
    'id',
    'trip_id',
    'trip_item_id',
    'author_id',
    'body',
    'is_task',
    'task_state',
    'assignee_user_id',
    'task_tag_id',
    'phase',
    'due_date',
    'resolved_at',
    'resolved_by_user_id',
    'parent_id',
    'title',
    'edited_at',
    'excursion_id',
    'position',
    'idea_id',
    'created_at',
    'field_hlcs',
    'updated_hlc',
  ],
  note_acks: [
    'id',
    'trip_id',
    'comment_id',
    'user_id',
    'acked',
    'seen_through',
    'field_hlcs',
    'updated_hlc',
  ],
  shopping_entries: [
    'id',
    'trip_id',
    'name',
    'list',
    'bought',
    'tag',
    'bought_at',
    'bought_by_user_id',
    'due_date',
    'assignee_user_id',
    'carried_over_at',
    'position',
    'idea_id',
    'field_hlcs',
    'updated_hlc',
  ],
  excursions: [
    'id',
    'trip_id',
    'name',
    'starts_on',
    'ends_on',
    'source_template_id',
    'idea_id',
    'field_hlcs',
    'updated_hlc',
  ],
  excursion_travelers: [
    'id',
    'trip_id',
    'excursion_id',
    'traveler_id',
    'field_hlcs',
    'updated_hlc',
  ],
  excursion_items: [
    'id',
    'trip_id',
    'excursion_id',
    'trip_item_id',
    'source_item_id',
    'name',
    'category_name',
    'assigned_traveler_id',
    'quantity',
    'packed_count',
    'state',
    'mode',
    'bought_at',
    'not_in_luggage',
    'for_all_participants',
    'shopping_position',
    'field_hlcs',
    'updated_hlc',
  ],
  excursion_tracks: [
    'id',
    'trip_id',
    'excursion_id',
    'name',
    'file_name',
    'kind',
    'with_kid',
    'pause_min',
    'position',
    'gpx_hash',
    'distance_m',
    'ascent_m',
    'descent_m',
    'max_ele_m',
    'point_count',
    'line',
    'field_hlcs',
    'updated_hlc',
  ],
  ideas: [
    'id',
    'trip_id',
    'author_id',
    'title',
    'note',
    'link',
    'tag',
    'rain_proof',
    'state',
    'created_at',
    'field_hlcs',
    'updated_hlc',
    'planned_on',
    'planned_at',
  ],
  idea_votes: ['id', 'trip_id', 'idea_id', 'user_id', 'vote', 'field_hlcs', 'updated_hlc'],
  idea_comments: [
    'id',
    'trip_id',
    'idea_id',
    'author_id',
    'body',
    'edited_at',
    'created_at',
    'field_hlcs',
    'updated_hlc',
  ],
  idea_images: ['id', 'trip_id', 'idea_id', 'image_hash', 'position', 'field_hlcs', 'updated_hlc'],
  day_entries: [
    'id',
    'trip_id',
    'author_id',
    'kind',
    'on_date',
    'at_time',
    'title',
    'note',
    'link',
    'legs',
    'excursion_id',
    'excursion_role',
    'field_hlcs',
    'updated_hlc',
  ],
  day_entry_travelers: [
    'id',
    'trip_id',
    'day_entry_id',
    'traveler_id',
    'field_hlcs',
    'updated_hlc',
  ],
  meals: [
    'id',
    'trip_id',
    'on_date',
    'slot',
    'title',
    'kind',
    'at_time',
    'note',
    'place',
    'cook_user_id',
    'excursion_id',
    'excursion_packed_at',
    'field_hlcs',
    'updated_hlc',
  ],
  meal_ingredients: [
    'id',
    'trip_id',
    'meal_id',
    'name',
    'amount',
    'list',
    'position',
    'bought',
    'bought_at',
    'bought_by_user_id',
    'shopping_position',
    'fresh',
    'field_hlcs',
    'updated_hlc',
  ],
  idea_tracks: [
    'id',
    'trip_id',
    'idea_id',
    'name',
    'file_name',
    'kind',
    'with_kid',
    'pause_min',
    'position',
    'gpx_hash',
    'distance_m',
    'ascent_m',
    'descent_m',
    'max_ele_m',
    'point_count',
    'line',
    'field_hlcs',
    'updated_hlc',
  ],
  trip_generated_positions: [
    'id',
    'trip_id',
    'trip_item_id',
    'source_template_id',
    'source_item_id',
    'traveler_id',
    'name',
    'quantity',
    'mode',
    'late_packer',
    'weight_grams',
    'value_cents',
    'category_name',
    'tasks',
    'field_hlcs',
    'updated_hlc',
  ],
} as const

/** A column of `T`. */
export type ColumnOf<T extends SyncTable> = (typeof TABLE_COLUMNS)[T][number]

/**
 * The columns a push may set — everything else is refused before any SQL is
 * built. Actor columns are not among them: the server stamps those.
 */
export const PUSHABLE_COLUMNS = {
  task_tags: ['name', 'sort_order', 'icon'],
  tags: ['name', 'sort_order', 'icon'],
  item_tags: ['item_id', 'tag_id', 'position'],
  items: [
    'name',
    'weight_grams',
    'value_cents',
    'created_by',
    'image_hash',
    'icon',
    'retired_at',
    'default_assignee_id',
    'merged_into_id',
  ],
  item_dependencies: ['item_id', 'depends_on_item_id', 'mode', 'quantity'],
  templates: ['owner_id', 'name', 'kind', 'icon', 'retired_at'],
  template_items: [
    'template_id',
    'item_id',
    'quantity',
    'assignment',
    'dedup',
    'conditions',
    'default_mode',
    'late_packer',
  ],
  template_includes: ['template_id', 'included_template_id'],
  template_item_tasks: ['template_item_id', 'task'],
  template_tasks: ['template_id', 'task', 'phase'],
  trip_series: ['owner_id', 'name', 'default_attributes'],
  destination_profiles: ['series_id', 'notes'],
  destination_checklist_items: ['profile_id', 'label', 'mode'],
  trips: [
    'series_id',
    'name',
    'year',
    'start_date',
    'end_date',
    'status',
    'attributes',
    'packing_closed_at',
    'imported',
    'created_by',
  ],
  trip_members: ['trip_id', 'user_id', 'role'],
  trip_template_sources: ['trip_id', 'template_id'],
  trip_applied_changes: [
    'trip_id',
    'source_template_id',
    'source_template_name',
    'kind',
    'item_name',
    'detail',
    'created_at',
  ],
  trip_items: [
    'trip_id',
    'source_item_id',
    'source_template_id',
    'name',
    'weight_grams',
    'value_cents',
    'category_name',
    'quantity',
    'packed_count',
    'state',
    'mode',
    'bought_from',
    'bought_at',
    'bought_by_user_id',
    'late_packer',
    'assigned_traveler_id',
    'packer_user_id',
    'packed_by_user_id',
    'packed_at',
    'container_id',
    'packing_now_by',
    'packing_now_at',
    'flag_unused',
    'flag_missing',
    'outbound_packed',
    'carried_over_at',
    'shopping_position',
  ],
  travelers: ['trip_id', 'name', 'linked_user_id'],
  containers: ['trip_id', 'name', 'carrier_traveler_id', 'max_weight_grams', 'paired_container_id'],
  comments: [
    'trip_id',
    'trip_item_id',
    'author_id',
    'body',
    'is_task',
    'task_state',
    'assignee_user_id',
    'task_tag_id',
    'phase',
    'due_date',
    'resolved_at',
    'resolved_by_user_id',
    'parent_id',
    'title',
    'edited_at',
    'excursion_id',
    'position',
    'idea_id',
    'created_at',
  ],
  note_acks: ['trip_id', 'comment_id', 'user_id', 'acked', 'seen_through'],
  shopping_entries: [
    'trip_id',
    'name',
    'list',
    'bought',
    'tag',
    'bought_at',
    'bought_by_user_id',
    'due_date',
    'assignee_user_id',
    'carried_over_at',
    'position',
    'idea_id',
  ],
  excursions: ['trip_id', 'name', 'starts_on', 'ends_on', 'source_template_id', 'idea_id'],
  excursion_travelers: ['trip_id', 'excursion_id', 'traveler_id'],
  excursion_items: [
    'trip_id',
    'excursion_id',
    'trip_item_id',
    'source_item_id',
    'name',
    'category_name',
    'assigned_traveler_id',
    'quantity',
    'packed_count',
    'state',
    'mode',
    'bought_at',
    'not_in_luggage',
    'for_all_participants',
    'shopping_position',
  ],
  excursion_tracks: [
    'trip_id',
    'excursion_id',
    'name',
    'file_name',
    'kind',
    'with_kid',
    'pause_min',
    'position',
    'gpx_hash',
    'distance_m',
    'ascent_m',
    'descent_m',
    'max_ele_m',
    'point_count',
    'line',
  ],
  ideas: [
    'trip_id',
    'author_id',
    'title',
    'note',
    'link',
    'tag',
    'rain_proof',
    'state',
    'created_at',
    'planned_on',
    'planned_at',
  ],
  idea_votes: ['trip_id', 'idea_id', 'user_id', 'vote'],
  idea_comments: ['trip_id', 'idea_id', 'author_id', 'body', 'edited_at', 'created_at'],
  idea_images: ['trip_id', 'idea_id', 'image_hash', 'position'],
  day_entries: [
    'trip_id',
    'author_id',
    'kind',
    'on_date',
    'at_time',
    'title',
    'note',
    'link',
    'legs',
    'excursion_id',
    'excursion_role',
  ],
  day_entry_travelers: ['trip_id', 'day_entry_id', 'traveler_id'],
  meals: [
    'trip_id',
    'on_date',
    'slot',
    'title',
    'kind',
    'at_time',
    'note',
    'place',
    'cook_user_id',
    'excursion_id',
    'excursion_packed_at',
  ],
  meal_ingredients: [
    'trip_id',
    'meal_id',
    'name',
    'amount',
    'list',
    'position',
    'bought',
    'bought_at',
    'bought_by_user_id',
    'shopping_position',
    'fresh',
  ],
  idea_tracks: [
    'trip_id',
    'idea_id',
    'name',
    'file_name',
    'kind',
    'with_kid',
    'pause_min',
    'position',
    'gpx_hash',
    'distance_m',
    'ascent_m',
    'descent_m',
    'max_ele_m',
    'point_count',
    'line',
  ],
  trip_generated_positions: [
    'trip_id',
    'trip_item_id',
    'source_template_id',
    'source_item_id',
    'traveler_id',
    'name',
    'quantity',
    'mode',
    'late_packer',
    'weight_grams',
    'value_cents',
    'category_name',
    'tasks',
  ],
} as const

/** A column of `T` a push may set. */
export type PushableColumnOf<T extends SyncTable> = (typeof PUSHABLE_COLUMNS)[T][number]

/** The values each text column's CHECK list allows, in the schema's order. */
export const COLUMN_ENUMS = {
  item_dependencies: {
    mode: ['required', 'suggested'],
  },
  templates: {
    kind: ['group', 'template'],
  },
  template_items: {
    assignment: ['per_person', 'trip_global'],
    dedup: ['max', 'sum'],
    default_mode: ['pack', 'buy_before', 'buy_local'],
  },
  destination_checklist_items: {
    mode: ['pack', 'buy_before', 'buy_local'],
  },
  trips: {
    status: ['planning', 'active', 'repack', 'archived'],
  },
  trip_members: {
    role: ['owner', 'admin', 'editor'],
  },
  trip_applied_changes: {
    kind: ['added', 'removed', 'changed'],
  },
  trip_items: {
    state: ['open', 'packing_now', 'partial', 'packed', 'skipped'],
    mode: ['pack', 'buy_before', 'buy_local'],
    bought_from: ['pack', 'buy_before', 'buy_local'],
  },
  comments: {
    task_state: ['open', 'resolved'],
  },
  shopping_entries: {
    list: ['buy_before', 'buy_local'],
  },
  excursion_items: {
    state: ['open', 'partial', 'packed', 'skipped'],
    mode: ['pack', 'buy_local'],
  },
  excursion_tracks: {
    kind: ['hike', 'bike'],
  },
  ideas: {
    tag: ['hiking', 'swimming', 'culture', 'food', 'outing'],
    state: ['idea', 'shortlisted', 'done', 'dropped'],
  },
  idea_votes: {
    vote: ['up', 'down'],
  },
  day_entries: {
    kind: ['note', 'connection'],
    excursion_role: ['out', 'back'],
  },
  meals: {
    slot: ['breakfast', 'lunch', 'snack', 'dinner'],
    kind: ['cook', 'out'],
  },
  meal_ingredients: {
    list: ['buy_before', 'buy_local'],
  },
  idea_tracks: {
    kind: ['hike', 'bike'],
  },
} as const

/** The vocabulary of column `C` of table `T`. */
export type ColumnEnum<
  T extends keyof typeof COLUMN_ENUMS,
  C extends keyof (typeof COLUMN_ENUMS)[T],
> = (typeof COLUMN_ENUMS)[T][C] extends readonly (infer V)[] ? V : never
