#!/usr/bin/env node
/**
 * Writes `client/src/i18n/zoneRegions.ts` — every IANA time zone of the tz
 * database's `zone.tab` with the country it belongs to. The app formats dates
 * and numbers by the region the device is in (NFR-4.12), and a browser names
 * that region only through its time zone: `navigator.languages` is the
 * device's *language*, which in an English-speaking Swiss household says US.
 *
 *   node scripts/zone-regions.mjs [/usr/share/zoneinfo/zone.tab]
 *
 * Rerun when the tz database adds a zone; an unknown zone falls back to the
 * language's own region, so a missing entry degrades rather than breaks.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const source = process.argv[2] ?? '/usr/share/zoneinfo/zone.tab'
const rows = readFileSync(source, 'utf8')
  .split('\n')
  .filter((line) => line && !line.startsWith('#'))
  .map((line) => line.split('\t'))
  .map(([country, , zone]) => [zone, country])
  .sort(([a], [b]) => a.localeCompare(b))

const body = rows.map(([zone, country]) => `  '${zone}': '${country}',`).join('\n')
const out = `/**
 * Each IANA time zone of the tz database's \`zone.tab\` and the country it lies
 * in — how the app learns the device's region (NFR-4.12). Generated by
 * \`scripts/zone-regions.mjs\`; never edited by hand.
 */
export const ZONE_REGIONS: Readonly<Record<string, string>> = {
${body}
}
`
writeFileSync(resolve(import.meta.dirname, '../client/src/i18n/zoneRegions.ts'), out)
console.log(`zone-regions: ${rows.length} zones written`)
